TestGroup/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TestGroup.Models;

namespace TestGroup.Controllers
{
    public class HomeController : Controller
    {
        testgroupEntities db = new testgroupEntities();

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string id)
        {
            StudentTestGroup student = db.StudentTestGroup
                .Where(a => a.StudentID == id)
                .SingleOrDefault();
            if (student != null)
            {
                Session["studentID"] = student.StudentID;
                return RedirectToAction("DoubleCheck", new { name = student.Name });
            }
            else
            {
                ViewBag.findNone = true;
                return View();
            }

        }

        public ActionResult DoubleCheck(string name)
        {
            Session["studentName"] = name;
            ViewBag.name = name;
            return View();
        }

        public ActionResult Logout()
        {
            Session["studentID"] = null;
            return View();
        }

        public ActionResult Index(string doAlert)
        {
            if (Session["studentID"] != null)
            {
                ViewBag.studentName = Session["studentName"];
                if (doAlert != "")
                {
                    switch (doAlert)
                    {
                        case "a": ViewBag.doAlert = "該單元已經完成嘍！辛苦了！ 請點擊「查看紀錄」連結，查看成果。"; break;
                        case "b": ViewBag.doAlert = "該單元「影片」時段未開放 (o*｡_｡)o sorry"; break;
                        case "c": ViewBag.doAlert = "該單元「答題」時段未開放 (o*｡_｡)o sorry"; break;
                        case "d": ViewBag.doAlert = "你這題答錯了喔！但是，該單元「訂正」時段未開放 (o*｡_｡)o sorry"; break;
                        default: break;
                    }
                }

                return View(db.Unit.ToList());
            }
            return RedirectToAction("Login");
        }

        [HttpPost, ActionName("Index")]
        public ActionResult KillOrder()
        {
            String studentID = Session["studentID"] + "";
            db.StudentTestGroup_Unit_Junction.RemoveRange(
                db.StudentTestGroup_Unit_Junction.Where(a => a.StudentID == studentID)
                );
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Resources()
        {
            if (Session["studentID"] != null)
            {
                string studentID = Session["studentID"] + "";
                var records = db.StudentTestGroup_Unit_Junction
                    .Where(a => a.StudentID == studentID && (a.Result == true || a.ExtendQuestionAnswer != null))
                    .OrderBy(a => a.UnitID);
                List <Unit> units = new List<Unit>();
                foreach (var record in records)
                {
                    Unit unit = db.Unit.Where(a => a.UnitID == record.UnitID).Single();
                    units.Add(unit);
                }
                Object[] idList = db.Unit.OrderBy(a => a.UnitID).Select(a => a.UnitID).ToArray();
                ViewBag.idList = idList;
                return View(units);
            }
            return RedirectToAction("Login");
        }



        public ActionResult Contact()
        {
            return View();
        }
    }
}

TestGroup/Controllers/UnitController.cs
using TestGroup.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Helpers;
using System.Text;

namespace TestGroup.Controllers
{
    public class UnitController : Controller
    {
        testgroupEntities db = new testgroupEntities();


        // GET: Unit
        public ActionResult WatchVideo(string id)
        {
            if (Session["studentID"] != null && id != null) //防呆未登入
            {
                //sortingHat(id);

                #region sortingHat

                Session["unitID"] = id; //這個到底用不用得到啊？？？
                string studentID = (string)Session["studentID"];


                //找這個人的這一題有沒有紀錄
                StudentTestGroup_Unit_Junction record = db.StudentTestGroup_Unit_Junction
                    .Where(a => a.StudentID == studentID && a.UnitID == id)
                    .SingleOrDefault();

                //如果這個人沒紀錄的話就創一個空的
                if (record == null)
                {
                    StudentTestGroup_Unit_Junction stuffToAdd = new StudentTestGroup_Unit_Junction()
                    {
                        StudentID = studentID,
                        UnitID = id,
                        VideoWatched = false,
                        ChatbotFinished = false,
                        ConceptMapAnswer = ""
                    };
                    db.StudentTestGroup_Unit_Junction.Add(stuffToAdd);
                    db.SaveChanges();

                    Session["record"] = stuffToAdd;
                }

                //如果有紀錄的話，就看這人做到哪一階段，就redirect到哪邊
                else
                {
                    Session["record"] = record;
                    if (record.ChatbotFinished && record.Result == false && record.ExtendQuestionAnswer == null) //答錯，已經看過concept map，還沒答相似題
                    {
                        return RedirectToAction("ExtendQ", new { secret = Crypto.HashPassword(record.StudentID) });
                    }
                    if (record.ChatbotFinished && record.Result == false) //答錯，已經看過concept map
                    {
                        return RedirectToAction("Index", "Home", new { doAlert = "a" });
                    }
                    if (!record.ChatbotFinished && record.Result == false) //答錯，未看concept map
                    {
                        return RedirectToAction("Chatbot");
                    }
                    if (record.Answer != null && record.Result == true) //答對
                    {
                        return RedirectToAction("Index", "Home", new { doAlert = "a" });
                    }
                    if (record.VideoWatched && record.Answer == null) //看完影片，未答題
                    {
                        return RedirectToAction("Question");
                    }
                }
                #endregion


                //Set ViewBags
                Unit unit = db.Unit.Where(u => u.UnitID == id).Single();
                if (unit.VideoStartDate.Value < DateTime.Now && unit.VideoEndDate > DateTime.Now) //在開放時間內 (其實index的button已經擋掉了，這裡是防直接用網址連進來的)
                {
                    return View(unit);
                }
                else
                {
                    return RedirectToAction("Index", "Home", new { doAlert = "b" });
                }
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult WatchVideo(DateTime startTime)
        {
            //StudentTestGroup_Unit_Junction record = (StudentTestGroup_Unit_Junction)Session["record"];
            if (ModelState.IsValid)
            {
                string studentID = Session["studentID"] + "";
                string unitID = Session["unitID"] + "";
                StudentTestGroup_Unit_Junction recFromDB = db.StudentTestGroup_Unit_Junction
                    .Where(a => a.StudentID == studentID && a.UnitID == unitID)
                    .Single();
                recFromDB.VideoWatched = true;
                recFromDB.VideoElapsedTime = (int)DateTime.Now.Subtract(startTime).TotalSeconds;
                db.SaveChanges();
                Session["record"] = recFromDB;
                return RedirectToAction("Question");
            }
            return View();
        }

        public ActionResult Question()
        {
            if (Session["studentID"] != null)
            {
                //先找有沒有紀錄
                StudentTestGroup_Unit_Junction record = (StudentTestGroup_Unit_Junction)Session["record"];

                //我不知道為什麼session == null會失靈，結果產生以下奇葩的code @@"，but it still works......
                //有紀錄的人......
                if (record != null)
                {
                    if (record.Answer != null || !record.VideoWatched) //已經答題or影片沒看的人，都給老子滾回首頁，來亂的
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    Unit unit = record.Unit; //有紀錄，尚未達題者請進，應該是從WatchVideo來的 or 看完影片中途跳開的
                    if (unit.QuestionStartDateTime.Value < DateTime.Now && unit.QuestionEndDateTime > DateTime.Now) //在開放時間內 (其實index的button已經擋掉了，這裡是防直接用網址連進來的)
                    {
                        return View(unit);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home", new { doAlert = "c" });
                    }
                }
                //else
                //{
                //沒紀錄的話給老子滾回首頁
                return RedirectToAction("Index", "Home");
                //}
            }
            return RedirectToAction("Login", "Home");
        }

        [HttpPost]
        public ActionResult Question(String answer, DateTime startTime)
        {
            string studentID = Session["studentID"] + "";
            string unitID = Session["unitID"] + "";
            StudentTestGroup_Unit_Junction recFromDB = db.StudentTestGroup_Unit_Junction
                .Where(a => a.StudentID == studentID && a.UnitID == unitID)
                .Single();
            recFromDB.QuestionElapsedTime = (int)DateTime.Now.Subtract(startTime).TotalSeconds;
            recFromDB.Answer = answer;

            //對答案
            String[] answers = db.Unit
                .Where(a => a.UnitID == unitID)
                .Single()
                .Answer
                .Split(',');
            recFromDB.Result = Array.Exists(answers, element => element == answer.ToUpper());
            db.SaveChanges();
            Session["record"] = recFromDB;
            if ((bool)recFromDB.Result)
            {
                return RedirectToAction("Congrats");
            }
            return RedirectToAction("Chatbot");
        }

        public ActionResult Congrats()
        {
            if (Session["studentID"] != null)
            {
                return View();
            }
            return View();
        }

        public ActionResult Chatbot()
        {
            if (Session["studentID"] != null)
            {
                //先找有沒有紀錄
                StudentTestGroup_Unit_Junction record = (StudentTestGroup_Unit_Junction)Session["record"];

                //我不知道為什麼session == null會失靈，結果產生以下奇葩的code @@"，but it still works......
                //有紀錄的人......
                if (record != null)
                {
                    if (record.ChatbotFinished || record.Result == true || record.Result == null) //已經讀過的人給老子滾回首頁，來亂的 (我要申明！！record.Result是nullable的！！！ ((( 從來沒想過有天會寫出 == true的智障code (╬▔皿▔)╯  )
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    Unit unit = record.Unit; //有紀錄，尚未達題者請進，應該是從WatchVideo來的 or 看完影片中途跳開的
                    if (unit.ConceptMapStartDate.Value < DateTime.Now && unit.ConceptMapEndDate > DateTime.Now) //在開放時間內 (其實index的button已經擋掉了，這裡是防直接用網址連進來的)
                    {
                        //如果有鍋的chatbot訂正劇本
                        if (unit.MultipleChatbot == true)
                        {
                            string[] agentIDs = unit.MultipleChatbotAgentID.Split('/');
                            ViewBag.AgentID = agentIDs[int.Parse(record.Answer) - 1]; //上面split完了，index從0開始，所以選項編號要減一
                        }
                        //製作完成連結密碼
                        ViewBag.secret = Crypto.HashPassword(record.StudentID);
                        return View(unit);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home", new { doAlert = "d" });
                    }
                }
                else
                {   //沒紀錄的話給老子滾回首頁
                    return RedirectToAction("Index", "Home");
                }
            }
            return RedirectToAction("Index", "Home");
        }

        //ExtendQuestion 為了避免跟資料表同名而縮減
        public ActionResult ExtendQ(string secret)
        {
            if (Session["studentID"] != null)
            {
                //先找有沒有紀錄
                StudentTestGroup_Unit_Junction record = (StudentTestGroup_Unit_Junction)Session["record"];

                //我不知道為什麼session == null會失靈，結果產生以下奇葩的code @@"，but it still works......
                //有紀錄的人......
                if (record != null)
                {
                    if (!(record.Result == false && record.ExtendQuestionAnswer == null)) //如果不是需要回答相似題的人，都滾
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    Unit unit = record.Unit; //有紀錄，尚未達題者請進，應該是從WatchVideo來的 or 看完影片中途跳開的
                    if (unit.ConceptMapStartDate.Value < DateTime.Now && unit.ConceptMapEndDate > DateTime.Now) //在開放時間內 (其實index的button已經擋掉了，這裡是防直接用網址連進來的) 不要驗證ConceptMapRead，因為底下才會改，不會有作弊嫌疑，因為secret猜不到
                    {
                        if (Crypto.VerifyHashedPassword(secret, record.StudentID))

TestGroup/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TestGroup/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "聯絡資訊";
}

<style>
    .whiteBlockHead {
        border-radius: 30px 30px 0px 0px;
        margin: -30px -30px 20px -30px;
        padding: 15px 20px 1px 20px;
        background-color: #ffcccc;
        text-align: center;
        font-weight: 900;
        font-size: 45px
    }

    .wideLine {
        border: 0;
        height: 4px;
        background-image: linear-gradient(to right, rgba(0, 0, 0, 0), rgb(153, 0, 0), rgba(0, 0, 0, 0));
    }

    .pd {
        padding-bottom: 20px
    }
</style>
<h1>~</h1>
<h1>@ViewBag.Title</h1>
<h1>~</h1>

<div class="whiteBlock shadow">
    <div class="whiteBlockHead">
        陳韻安
        <hr class="wideLine" />
    </div>
    <div class="row">
        @*<div class="col-sm-2 pd"><b>FB：</b></div> <div class="col-sm-10 pd"><a href="https://www.facebook.com/vivian.pony/" target="_blank" class="glyphicon glyphicon-link">陳韻安</a></div>*@
        <div class="col-sm-2 pd"><b>信箱：</b></div> <div class="col-sm-10 pd"><a href="mailto:vivian0602.chen@gmail.com"> 📧 vivian0602.chen@gmail.com</a></div>
        <div class="col-sm-2 pd"><b>發問題格式：</b></div>
        <div class="col-sm-10 pd">
            <b>Messenger</b>或是<b>寫信</b>都可以喔！我會盡快回覆！ <br />以下幾點有的話盡量寫，會比較明確，可以避免溝通上的誤解 (〃￣︶￣)人(￣︶￣〃) <br> <br />
            <b>信件主旨：</b> 【資料結構 學習系統問題】資二A 07156XXX 王大明 <br>
            <b>內容：</b> <br>
            <ul>
                <li>第？週 第？題</li>
                <li>問題描述 / 網頁錯誤描述：</li>
                <li>連絡後想達成的目的：</li>
                <li>頁面截圖：</li>
            </ul>
        </div>
    </div>

</div>

TestGroup/Views/Home/DoubleCheck.cshtml
@{
    ViewBag.Title = "再次確認";
}

<link href="~/Content/midleBlock.css" rel="stylesheet" />
<div class="middleBlock shadow2">
    <h2 class="col-md-offset-1">再次確認</h2>
    <hr class="wideLine" />
    <h3 class="col-md-offset-1">請問你是 <strong>@ViewBag.name</strong> 嗎？</h3>
    <div class="row">
        <div class="col-sm-6 ">
            @Html.ActionLink("是", "Index", null, new { @class = "yes btn" })
        </div>
        <div class="col-sm-6 ">
            @Html.ActionLink("否", "Login", null, new { @class = "no btn" })
        </div>
    </div>

</div>

TestGroup/Views/Home/Index.cshtml
@model IEnumerable<TestGroup.Models.Unit>

@{
    ViewBag.Title = "首頁";
}
<style>
    .week {
        display: block;
        margin: auto auto 20px auto;
        max-width: 90%;
        align-items: center;
        background-color: #396060;
        border-radius: 30px;
        padding: 20px;
        font-size: 20px;
        color: white;
    }

    .weekText {
        font-size: 50px;
        color: #DAA520;
        font-weight: 900;
    }

    .questionNumber {
        font-weight: 900;
        font-size: 30px;
        padding-top: 10px;
        text-align: center
    }

    .keyWords {
        text-align: left;
        display: -webkit-box;
        -webkit-line-clamp: 2;
        -webkit-box-orient: vertical;
        overflow: hidden;
    }
    .wideLine {
        border: 0;
        height: 3px;
        background-image: linear-gradient(to right, rgba(0, 0, 0, 0), rgb(153, 0, 0), rgba(0, 0, 0, 0));
    }
</style>
<h1>歡迎</h1>
<h1>@ViewBag.StudentName</h1>
<h1>!</h1>
<br />
<div name="allThreeWeeks" class="container">
    @{int j = 0;}

    @for (int i = 1; i <= Model.Last().Week; i++)
    {
        <div name="week_@i" class="row week shadow2">
            <div class="col-md-1 weekText">第 @i 週</div>
            <div class="col-md-11">
                @for (; j < Model.Count(); j++)
                {
                    TestGroup.Models.Unit unit = Model.ToList().ElementAt(j);
                    if (unit.Week == i)
                    {
                        <div class="row">
                            <div class="col-md-2 questionNumber">第 @unit.Number 題</div>
                            <div class="col-md-3 keyWords">@unit.KeyWords</div>
                            <div class="col-md-5">
                                影片：@unit.VideoStartDate.Value.ToShortDateString() ~ @unit.VideoEndDate.Value.AddDays(-1).ToShortDateString()
                                <br />答題：@unit.VideoEndDate.Value.ToShortDateString() 實習課上課回答
                                <br />訂正：@unit.ConceptMapStartDate.Value.ToShortDateString() ~ @unit.ConceptMapEndDate.Value.AddDays(-1).ToShortDateString()
                            </div>
                            <div class="col-md-2 row">
                                @if (unit.VideoStartDate.Value < DateTime.Now && unit.ConceptMapEndDate > DateTime.Now)
                                {
                                    <div class="col-md-12" style="margin-bottom:10px">@Html.ActionLink("開始學習", "WatchVideo", "Unit", new { id = unit.UnitID }, new { @class = "btn default" })</div>
                                }
                                else
                                {
                                    <div class="col-md-12" style="margin-bottom:10px"><a class="btn default" href="~/Home/Index" onclick="return alert('該單元時段未開放 (o*｡_｡)o sorry')">開始學習</a></div>
                                }
                                <div class="col-md-12">@Html.ActionLink("查看紀錄", "Progress", "Unit", new { id = unit.UnitID }, new { @class = "btn default" })</div>
                            </div>
                        </div>
                        <hr class="goldLine" />
                    }
                    else
                    {
                        break;
                    }
                }
            </div>
        </div>

    }
</div>


@if (ViewBag.doAlert != null)
{
    <script>
    var msg = "@ViewBag.doAlert";
    alert(msg);
    </script>
}

@* 重制按鈕 Reset Button *@
<div class="whiteBlock">
    @using (Html.BeginForm())
    {
        <h2>清除以上進度 Clear All Progress</h2>
        <hr class="wideLine" />
        <h4>若本帳號已完成所有練習，請按此按鈕，清空學習紀錄，繼續體驗學習區功能 </h4>
        <h4>這是demo版的功能，在實際學生操作版上沒有 </h4>
        <h4>click this button to clear all learning progress if all the exercises were completed on this account</h4>
        <h4>this feature only exists on this demo version, it's not available to students </h4>
        <input type="submit" value="清除 Clear" class="btn no btn-danger" onclick="return confirm('⚠清除後紀錄都會不見喔！ The records will disappear after reset!')" />
    }
</div>

@* 重制按鈕 Reset Button *@

TestGroup/Views/Home/Login.cshtml
@{
    ViewBag.Title = "登入";
}
<link href="~/Content/midleBlock.css" rel="stylesheet" />
<style>
    div.chat-wrapper[opened="true"] {
        height: 73% !important;
        width: 35% !important;
    }
</style>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal middleBlock shadow2">
        <h2 class="col-md-offset-1">登入</h2>
        <hr class="wideLine" />
        <div class="form-group">
            <label class="control-label col-md-4" for="StudentID"><b>請輸入學號：</b></label>
            <div class="col-md-8">
                <input class="form-control text-box single-line" type="text" name="id" required>
                @if (ViewBag.findNone != null)
                {
                    <p>沒有這個學號</p>
                }
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="登入" class="btn default" />
            </div>
        </div>
    </div>
}

TestGroup/Views/Home/Logout.cshtml
@{
    ViewBag.Title = "登出";
}
<link href="~/Content/midleBlock.css" rel="stylesheet" />

<div class="middleBlock shadow2">
    <h2 class="col-md-offset-1">BYE~~</h2>
    <hr class="wideLine" />
    <p class="col-md-offset-1">你已經登出了，想再回來，請先登入。</p>
    @Html.ActionLink("登入", "Login", null, new { @class = "btn default" })
</div>

TestGroup/Views/Home/Resources.cshtml
@model IEnumerable<TestGroup.Models.Unit>
@{
    ViewBag.Title = "單元回顧";
}
<style>
    .thumbnail {
        padding: 15px;
        border: none;
        color: #DAA520;
        font-size: 30px;
        height: 300px;
    }
    .greenbg {
        background-color: #396060;
    }
    .graybg {
        background-color: #d9d9d9;
    }
    .locked {
        position: relative;
        margin: 35px;
        width:100px;
        height: 100px
    }
    .graytext {
        color: #b3b3b3;
    }
    .keywords {
        display: -webkit-box;
        -webkit-line-clamp: 1;
        -webkit-box-orient: vertical;
        overflow: hidden;
    }

    .modal {
        background-image: url('../../Pictures/popoutbackground.jpg');
        background-repeat: no-repeat, repeat;
        background-size: cover;
        background-attachment: scroll;
    }

    .modal-header, .modal-body, .modal-footer {
        background-color: #396060;
        color: #DAA520;
        font-size: 20px;
    }

    .modal-header {
        text-align: center;
    }

    .modal-body {
        text-align: left;
    }

    .modal-footer {
        text-align: right;
    }

    .modal-header, .modal-body {
        padding: 10px;
    }
</style>

<h1>影片</h1>
<h1>&</h1>
<h1>題型</h1>
@{int count = 0;}
<div class="row text-center">
    @foreach (var unit in Model)
    {
        for (; ViewBag.idList[count] != unit.UnitID && count < ViewBag.idList.Length; count++) //未完成
        {
            <div class="col-md-4 col-sm-6" style="height:350px">
                <div class="thumbnail graybg shadow">
                    <img class="locked" src="~/picture/locked.png" />
                    <p class="graytext"><strong>未解鎖QAQ</strong></p>
                </div>
            </div>
        }
        //已完成
        <div class="col-md-4 col-sm-6" style="height:350px">
            <div class="thumbnail greenbg shadow">
                @*<iframe src="@item.VideoLink" style="border-radius:25px" onclick=""></iframe>*@
                <div style="max-width: 300px; height: 150px; position: relative;margin:auto">
                    <iframe src="@unit.VideoLink" frameborder="0" scrolling="no" style="width: 100%; max-width: 300px; height: 150px; border-radius: 25px "></iframe>
                    <div style="width: 80px; height: 80px; position: absolute; opacity: 0; right: 0px; top: 0px;"> </div>
                </div>
                <p>
                    <strong>第 @unit.Week 週 的 第 @unit.Number 題</strong> <br />
                    <small><small><small class="keywords">@unit.KeyWords</small></small></small>
                </p>

                <input type="button" class="btn default" data-toggle="modal" data-target="#@unit.UnitID" value="查看內容">
            </div>
        </div>

        <!-- Modal -->
        <div class="modal fade shadow" id="@unit.UnitID" role="dialog">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">×</button>
                        <h2><strong><span class="glyphicon glyphicon-film"></span> 第 @unit.Week 週 的 第 @unit.Number 題 </strong> </h2>
                    </div>
                    <div class="modal-body">
                        @*<iframe src="@item.VideoLink" style="width:100%; height:65vh; margin:5px" allowfullscreen></iframe>*@

                        <div style="width: 100%; height: 480px; position: relative;margin:auto">
                            <iframe src="@unit.VideoLink" width="100%" height="480" frameborder="0" scrolling="no" seamless="" allowfullscreen></iframe>
                            <div style="width: 80px; height: 80px; position: absolute; opacity: 0; right: 0px; top: 0px;"> </div>
                        </div>


                        <p>
                            <strong>關鍵字：</strong> @unit.KeyWords <br /><br />
                            <strong>題目：</strong>@unit.Question
                            @*<img src="@(item.QuestionImageLink)" style="max-width: 70%; margin:0% 15% 0% 15%" />*@
                            @if (unit.QuestionImageLink != null)
                            {
                                @* 【注意】以下圖片是放在google硬碟https://drive.google.com/drive/folders/1RmAtSzaMKTU0rlaqr3rKMBR9PGVpOZUA?usp=sharing，用google寫好的方式embed進來的 *@
                                <div style=" position: relative; max-width: 100%;">
                                    <iframe src="@(unit.QuestionImageLink)" style="width: 100%; height: 400px" allow="autoplay"></iframe>
                                    <div style="width: 60px; height: 60px; position: absolute; opacity: 0; right: 0px; top: 0px;"> </div>
                                </div>
                            }
                            <br />
                            <strong>答案：</strong>
                            @if (unit.MultipleChoice == true)
                            {
                                string[] mapAns = { "?", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J" };
                                string ans = mapAns[int.Parse(unit.Answer)];
                                <b>正確解答：</b> @ans <br /><br />
                            }
                            else
                            {
                                @unit.Answer.Split(',').First() <br /><br />
                            }
                            <strong>概念構圖與解釋：</strong>@Html.Raw(unit.ConceptMapDescription)
                            @* 【注意】以下圖片是放在google硬碟https://drive.google.com/drive/folders/1RmAtSzaMKTU0rlaqr3rKMBR9PGVpOZUA?usp=sharing，用google寫好的方式embed進來的 *@
                            <div style="position: relative ">
                                <iframe src="@(unit.ConceptMapLink)" style="width: 100%; height: 500px" allow="autoplay"></iframe>
                                <div style="width: 60px; height: 60px; position: absolute; opacity: 0; right: 0px; top: 0px;"> </div>
                            </div>
                        </p>

                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn no pull-left" data-dismiss="modal">
                            <span class="glyphicon glyphicon-remove"></span> 關閉
                        </button>
                        <p>需要 <a href="~/Home/Contact" style="color: #DAA520"><strong>協助</strong></a> 嗎？</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Modal -->
        count++;
    }
    @* 把剩下沒有完成的單元方塊跑完 *@
    @for (; count < ViewBag.idList.Length; count++) //未完成
    {
        <div class="col-md-4 col-sm-6" style="height:350px">
            <div class="thumbnail graybg shadow">
                <img class="locked" src="~/picture/locked.png" />
                <p class="graytext"><strong>未解鎖QAQ</strong></p>
            </div>
        </div>
    }
</div>



<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h4><span class="glyphicon glyphicon-film"></span>標題</h4>
            </div>
            <div class="modal-body">

            </div>
        </div>
    </div>
</div>